name: C++ to EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile
        shell: cmd
        run: |
          g++ *.cpp -o hilya.exe

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: hilya-exe
          path: hilya.exe
