name: C++ to EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile CPP
        run: g++ main.cpp -o main.exe

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: main-exe
          path: main.exe
